materialsproject/fireworks

fireworks/user_objects/queue_adapters/Cobalt_template.txt
fireworks/user_objects/queue_adapters/common_adapter.py
fw_tutorials/queue/qadapter_cobalt.yaml

Patches for base Cobalt support.

Cobalt support

---

fireworks/user_objects/queue_adapters/common_adapter.py

common_adapter: fix njobs for SLURM

---

fireworks/core/firework.py

Hi,
this pull request provides methods to merge workflows together. I needed this functionality for the MoDeNa project (https://github.com/MoDeNa-EUProject/MoDeNa) because I would like to build the workflows step by step. Please let me know whether this is acceptable - I am happy to apply changes or rethink the design.
Best Regards,
Henrik

ENH: Added methods to merge workflows together

---

fireworks/core/launchpad.py

launchpad: catch LockedWorkflowError

---

fireworks/core/firework.py

In my opinion there are two issues:
a) If the check fails it potentially leaves an half-finished Workflow for somebody in case somebody is trying to recover from the ValueError.
b) The check is executed len(new_wf.fws) time which is unnecessary.
Henrik

ENH: Reduce complexity of append_wf by moving check out of loop

---

fireworks/queue/queue_launcher.py

Fix datetime import

---

fireworks/queue/queue_launcher.py
requirements.txt
setup.py

It should be better to unreserve the FW at the end of the queue launch process.

Always unreserve if something went wrong

---

fireworks/flask_site/app.py
requirements.txt

Simple user+password authentication. Optional. No effect if user and password are not set.
Pls release new version so that can be used with pip install.

Simple auth for Fireworks Flask site

---

fireworks/core/firework.py
fireworks/core/launchpad.py

* remove code duplications: merge reserve_fw and checkout_fw, merge mark_fizzled and complete_checkout
* update get_representative_launch to return the most recent completed one.
* update/cleanup documentation

refactor: remove code duplications

---

fireworks/user_objects/queue_adapters/SLURM_template.txt

Required on Cori after integration.

Support for --constraint for SLURM

---

docs/defuse_tutorial.rst
fireworks/core/launchpad.py
fireworks/core/tests/test_launchpad.py
fireworks/scripts/lpad_run.py

Added in test for pause_wf
Added in pause_wf into LaunchPad
Added in lpad pause_wflows
Added doc on pause_wflows

Pause WorkFlow

---

docs/duplicates_tutorial.rst
docs/dynamic_wf_tutorial.rst
docs/failures_tutorial.rst
docs/firetask_tutorial.rst
docs/introduction.rst
docs/priority_tutorial.rst
docs/queue_tutorial.rst
docs/templatewritertask.rst
docs/worker_tutorial.rst
docs/workflow_tutorial.rst

Minor updates to tutorial docs to clarify distinction between FireServer and LaunchPad.

Minor updates to docs

---

docs/multi_job.rst
fireworks/scripts/rlaunch_run.py

Added multi command to rlaunch
Ported mlaunch parser to rlaunch

Merge mlaunch into rlaunch command

---

docs/filepad_tasks.rst
docs/filepad_tutorial.rst
fireworks/user_objects/firetasks/filepad_tasks.py
fireworks/user_objects/firetasks/tests/test_filepad_tasks.py
fireworks/utilities/filepad.py
fireworks/utilities/tests/test_filepad.py

* remove additional_data
* cleanup and update doc

minor refactor in filepad

---

fireworks/user_objects/firetasks/filepad_tasks.py
fireworks/user_objects/firetasks/tests/test_filepad_tasks.py
fireworks/utilities/filepad.py
fireworks/utilities/tests/test_filepad.py

* add "compressed" bool key
* delete old file contents on update
* add build_indexes and reset
* add/update unittests

filepad updates

---

docs/changelog.rst
fireworks/core/launchpad.py
fireworks/scripts/lpad_run.py

Fix changelog
Add --mongo flag to use direct mongo syntax in update_fws
Add mongo flag into update_spec

Add in MongoDB syntax into update_fws

---

docs/firetask_tutorial.rst

Fix typo in firetask_tutorial.rst

---

docs/rerun_tutorial.rst

launches be --> launches can be

Fix typo in rerun_tutorial.rst

---

fireworks/core/rocket.py
fireworks/core/rocket_launcher.py
fireworks/features/multi_launcher.py
fireworks/scripts/rlaunch_run.py
fireworks/utilities/fw_utilities.py

Redirect stdout to fws.out and stderr to fws.error in the launch directory
Available for rlaunch rapidfire and rlaunch multi

Added an option to redirect stdout and stderr to the launch directory

---

fireworks/core/firework.py
fireworks/core/tests/test_firework.py

* remove fireworks corresponding to the given fw ids
* added tests
* note: was orginally in atomate

add remove_fws method to Workflow

---

fireworks/features/fw_report.py

Usage:
```
fw_report = FWReport(lpad)
plt = fw_report.plot_stats()
plt.show()
```

Plot report

---

fireworks/core/launchpad.py
fireworks/core/rocket_launcher.py

Fixes #233 
Makes rapidfire with nlaunches=0 only quit once there are no more READY or WAITING launches

rapidfire until completion

---

fireworks/utilities/dagflow.py
fireworks/utilities/tests/test_dagflow.py

This contains two small fixes after https://github.com/materialsproject/fireworks/pull/256. See the code differences, it is not much.

empty firework list and type check

---

docs/_sources/firetask_tutorial.rst.txt

Adding docs to overcome confusion from #295

Update firetask tutorial

---

metadata.yml

see FAQs at https://www.osti.gov/doecode/faq  
metadata can be updated as needed

add fireworks to DoeCode

---

.circleci/config.yml
requirements.txt

Mainly to see if circleci throws error (tests ran ok for me locally) using pymongo 3.7.0
Please do not merge until #299 is resolved.

Upgrade pymongo version to 3.7.0

---

fireworks/core/launchpad.py

Looks like this isn't actually an argument

fixed docs for LaunchPad.pause_wf

---

fireworks/flask_site/app.py
fireworks/flask_site/util.py

Pass MongoJSONEncoder to flask.json.jsonify

---

fireworks/features/introspect.py

in compare_stats() convert statsdict1.keys to list

---

fireworks/queue/queue_launcher.py
fireworks/scripts/qlaunch_run.py

qlaunch rapidfire add new --block_dir flag

---

fireworks/core/firework.py
fireworks/core/launchpad.py
fireworks/core/rocket.py
fireworks/core/tests/test_firework.py
fireworks/core/tests/test_launchpad.py
fireworks/fw_config.py
fireworks/user_objects/firetasks/script_task.py
fireworks/utilities/dagflow.py
fireworks/utilities/fw_utilities.py
requirements.txt
setup.py

Also adds a few type hints.
Added a test for the `Workflow` `__len__` and `__iter__ ` but couldn't find the test class for `Fireworks`.

Implement __len__ + __iter__ for Firework + Workflow

---

docs_rst/dynamic_wf_tutorial.rst
docs_rst/firetask_tutorial.rst
docs_rst/guide_to_writing_firetasks.rst
fireworks/core/firework.py
fireworks/core/launchpad.py
fireworks/core/rocket.py
fireworks/queue/queue_launcher.py
fireworks/scripts/lpad_run.py
fireworks/scripts/qlaunch_run.py
fireworks/user_objects/firetasks/fileio_tasks.py

- 91ad4b31 flynt -a fireWorks
- 39e4eb0c update docs_rst too

Convert remaining format str to f-str

---

fireworks/scripts/lpad_run.py
fireworks/scripts/mlaunch_run.py
fireworks/scripts/qlaunch_run.py
fireworks/scripts/rlaunch_run.py
setup.py

add -v/--version to `lpad` + `{q,m,r}launch`

CLI version flags

---

docs_rst/security_tutorial.rst

After solving https://github.com/materialsproject/fireworks/issues/469 in PR https://github.com/materialsproject/fireworks/pull/471 the security tutorial in the docs has to be fixed. Here I updated it to reflect the changes.

Updated the docs regarding TLS configuration

---

.pre-commit-config.yaml
docs/_sources/installation.rst.txt
docs_rst/installation.rst
fireworks/core/firework.py
fireworks/core/rocket_launcher.py
fireworks/core/tests/test_launchpad.py
fireworks/queue/queue_launcher.py
fireworks/tests/test_fw_config.py
fireworks/user_objects/queue_adapters/tests/test_common_adapter.py
fireworks/utilities/fw_utilities.py
setup.cfg

Remove repeated words in doc strings

---

fireworks/tests/mongo_tests.py

I needed to add this following to the `mongo_tests.py` -- let me know if that's a property of my setup; or feel free to merge if it's a bug.

Add missing property in test

---

setup.py

Please see https://github.com/igraph/python-igraph/issues/699 for the explanation.

change 'python-igraph' dependency to 'igraph'

---

fireworks/core/firework.py
fireworks/core/launchpad.py
fireworks/core/rocket.py
fireworks/core/tests/test_launchpad.py
fireworks/features/fw_report.py
fireworks/features/introspect.py
fireworks/flask_site/helpers.py
fireworks/queue/queue_adapter.py
fireworks/scripts/lpad_run.py
fireworks/scripts/tests/test_lpad_run.py
fireworks/scripts/tests/test_qlaunch_run.py
fireworks/scripts/tests/test_rlaunch_run.py
fireworks/tests/master_tests.py
fireworks/tests/mongo_tests.py
fireworks/user_objects/firetasks/tests/test_dataflow_tasks.py
fireworks/user_objects/firetasks/tests/test_filepad_tasks.py
fireworks/user_objects/queue_adapters/common_adapter.py
fireworks/utilities/dagflow.py
fireworks/utilities/tests/test_filepad.py
fireworks/utilities/visualize.py

78cddaa4 fix ambiguous variable names
adcbd5c2 fix wrong type hint
9fc7cc47 fix ruff E402 Module level import not at top of file

Fix ambiguous var names

---

.circleci/config.yml
docs/_sources/installation.rst.txt
docs_rst/installation.rst
setup.py

To fix CircleCI f-string errors
<details><summary>Details</summary>
```py
E     File "<fstring>", line 1
E       (fw_id=)
E             ^
E   SyntaxError: invalid syntax
_ ERROR collecting fireworks/user_objects/firetasks/tests/test_script_task.py __
/opt/conda/envs/test-environment/lib/python3.7/site-packages/_pytest/python.py:617: in _importtestmodule
mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
/opt/conda/envs/test-environment/lib/python3.7/site-packages/_pytest/pathlib.py:565: in import_path
importlib.import_module(module_name)
/opt/conda/envs/test-environment/lib/python3.7/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1006: in _gcd_import
???
<frozen …
```

Bump minimum Python version to 3.8

---

.pre-commit-config.yaml
docs_rst/conf.py
fireworks/core/firework.py
fireworks/core/launchpad.py
fireworks/core/rocket.py
fireworks/core/rocket_launcher.py
fireworks/core/tests/test_firework.py
fireworks/core/tests/test_launchpad.py
fireworks/core/tests/test_tracker.py
fireworks/features/fw_report.py
fireworks/features/introspect.py
fireworks/fw_config.py
fireworks/scripts/lpad_run.py
fireworks/scripts/mlaunch_run.py
fireworks/scripts/qlaunch_run.py
fireworks/scripts/rlaunch_run.py
fireworks/tests/tasks.py
fireworks/user_objects/firetasks/dataflow_tasks.py
fireworks/user_objects/firetasks/script_task.py
fireworks/user_objects/firetasks/tests/test_filepad_tasks.py
fireworks/user_objects/firetasks/tests/test_templatewriter_task.py
fireworks/user_objects/queue_adapters/tests/test_common_adapter.py
fireworks/utilities/dagflow.py
fireworks/utilities/fw_serializers.py
fireworks/utilities/fw_utilities.py
fireworks/utilities/tests/test_update_collection.py
fireworks/utilities/visualize.py
pyproject.toml

`ruff` fixes
