materialsproject/fireworks

.coveragerc
.travis.yml

Nice way to track your test coverage. Took the liberty of setting up the `.coveragerc` file. Seems to be getting the right files, but maybe could be tuned to skip certain lines that one wishes to skip ( http://nedbatchelder.com/code/coverage/config.html ). Requires a Coveralls account for submission (free for open source). Uses Travis CI, but could be set up with another CI. See example output here ( https://coveralls.io/r/jakirkham/fireworks ).

Provide coverage information for each build using Coveralls

---

fireworks/core/rocket_launcher.py
fireworks/core/tests/test_launchpad.py

Fixes materialsproject/fireworks#98. I have verified that the tests fail when my solution is not included. Also, this works when testing in workflows.

Rapidfire switch back to cwd at the end.

---

fireworks/core/tests/test_launchpad.py

This is a workaround for issue materialsproject/fireworks#100. Until a better solution is found, skip the timed test with spurious failures.

Workaround for issue materialsproject/fireworks#100

---

fireworks/core/tests/test_launchpad.py

As mentioned in issue ( materialsproject/fireworks#100 ),the test, `test_rerun_timed_fws`, still has spurious failures as evidenced by the most recent builds on master ( https://travis-ci.org/materialsproject/fireworks/builds/65300009 ). So, bringing back the workaround until the problem is better understood and the necessary fix applied.

Restore workaround for issue materialsproject/fireworks#100

---

requirements.txt

It appears that `Flask-paginate` is needed to get the Web GUI running so added it as a requirement.

Add Flask-paginate as a requirement

---

fireworks/user_objects/queue_adapters/LoadSharingFacility_template.txt
fireworks/user_objects/queue_adapters/common_adapter.py

common_adapter.py currently supports IBM LoadLeveler, which has been replaced with IBM LoadSharingFacility (LSF).  
Adding support for LSF was pretty trivial; the only problem I found was that the job submission utility only processed the file headers (queue name, job name, etc) correctly when the file was read in through stdin (i.e. 'bsub < submissionfile').  This may be a problem with our local cluster installation; we currently use a custom wrapper that reads the file ahead of time and converts the header into command line arguments.  I don't think the proposed special-case for the submission (lines 140-145) would break support even if submitting as a file worked correctly on someone else's cluster.

add support for IBM LoadSharingFacility to common_adapter.py

---

fireworks/core/fworker.py

A user's `$or` query is overwritten in `fworker.query` and hence effectively ignored. This pull request fixes this issue by combining the user's `$or` query with the internal fworker check through an `$and` query.

fworker: fix query when user sets or-query

---

fireworks/user_objects/queue_adapters/SLURM_template.txt

We noticed when testing SLURM on NERSC's Carver that the submit script will not be able to load/find the necessary module unless a login shell is requested in the shebang line. This pull requests fixes it for the SLURM template but it might be necessary for the other templates, too.

SLURM_template: request login shell in shebang line

---

fireworks/features/fw_report.py

I'd like to run reports like
```bash
$ lpad report -i months -q '{"spec.mpsnl.about.remarks": "MP user submission"}'
```
but it seems the query arg is left as a `str`, so I get an `AttributeError: 'str' object has no attribute 'update'` [here](https://github.com/materialsproject/fireworks/blob/f112342dd26f06d5b4622f117ca2cc79679e7095/fireworks/features/fw_report.py#L52).
My PR fixes this issue for me so that I can run the above line with success.

Cast query arg to lpad report from str to dict

---

fireworks/core/firework.py

I'm having some trouble with fireworks that append new fireworks to a workflow as a result of the changes in commit 12d4958.  I get the error below when doing Add Electronic Structure Task, for example.  It seems like removing the refresh_wfs conditional near the end of append_wfs in fireworks.py fixes the issue, but there may be a more appropriate fix.
"2015-10-26 19:08:02,600 INFO Task completed: Add Electronic Structure Task v2
Traceback (most recent call last):
File "/global/u1/m/montoyjh/jhm_elastic/codes/fireworks/fireworks/core/rocket.py", line 298, in run
lp.complete_launch(launch_id, m_action, final_state)
File "/global/u1/m/montoyjh/jhm_elastic/codes/fireworks/fireworks/core/launchpad.py", line 886, in complete_launch
self._refresh_wf(fw_id)
File …

removed conditional on returning updated_ids in append_wf

---

fireworks/flask_site/app.py
fireworks/flask_site/templates/wf_metadata.html

* Takes a key/value pair, and optionally a state
* If only one result, redirect to wf_details view
* If multiple results, load specialization of wf_state view
The onus would be on users to ensure [appropriate indexes](https://pythonhosted.org/FireWorks/performance_tutorial.html#how-to-add-an-index-to-workflow-metadata).
Intended immediate application: `/wf/metadata/submission_id/\d+/` links to workflows spawned by materialsproject.org user submissions.

Add view for wf metadata queries

---

fireworks/core/launchpad.py
fireworks/scripts/lpad_run.py

Dr. Anubhav Jain,
I have added support for SSL connections via CA Certificates for Launchpad to MongoDB servers.  At the AFRL DoD Supercomputing Resource Center, they require two factor authentication for connections to DB servers and they deemed CA certificates were the best second level of authentication to implement for MongoDB servers.
Regards,
David Cossey

Adding SSL CA Certificate support to Launchpad

---

fireworks/core/launchpad.py
fireworks/core/tests/test_launchpad.py
fireworks/scripts/lpad_run.py

- only launches for worker specified by -w will be recovered (one needs to run the command on the actual worker anyway)
- recover_offline can optionally print the exceptions
- fix: recover_offline sets the state of the FW to running when needed
- tests

small improvements for offline mode

---

fireworks/user_objects/firetasks/fileio_tasks.py

Fixes [a misuse of `get`](https://github.com/materialsproject/fireworks/blob/master/fireworks/user_objects/firetasks/fileio_tasks.py#L98) in the `FileTransferTask` relevant for remote transfers. Also ensures that if `src` is a file, `dest` is still interpreted as a directory (as it should according to the class docstring).
Additionally, adds a `user` parameter for specifying the username to authenticate against on the remote server.
If this is too many things in one PR, I'm happy to split them up.

FileTransferTask bugfixes, added user parameter

---

fireworks/user_objects/firetasks/fileio_tasks.py

Added ``retry`` option to ``FileTransferTask``. It's a bit crude in that it just runs ``self.run_task`` again if the `try` block fails and the ``retry`` option is ``True``. As written it will keep trying until the recursion limit is reached.
Happy to adjust the way this is implemented to make it less crude. At the moment this is a (useful) hack I use to guard against remote transfer failures, which are frequent enough (for me) as to make this a must-have.

Feature filetransfer retry

---

docs/contributors.rst
fireworks/core/firework.py
fireworks/core/tests/test_firework.py

There are occasions in which a new Workflow needs to be created from an
existing one, but with updated Firework ids to ensure no collisions with
any Workflows it is appended to. Such collisions can occur when a
Workflow has been serialized and stored within a Firework spec, then
appended by that Firework to the Workflow it is a part of (as an ``addition``).
The result of these collisions are often malformed links.
Building a fresh Workflow from that stored avoids this problem, since
the member Fireworks are given fresh ids that have not been used within
the current session.

Can now make a fresh copy of an existing Workflow.

---

fireworks/user_objects/queue_adapters/common_adapter.py

Using ``qlaunch rapidfire --maxjobs_queue <NUM>`` for launching rockets to an SGE queue did not properly detect the number of jobs in the queue. This is because by default the ``qstat`` output doesn't include the queue assignment for jobs that are not yet running, so in the case where ``<NUM>`` is greater than the number of jobs actually running, jobs will continue to be submitted (especially for ``--nlaunches infinite``) well beyond ``<NUM>``.
This PR adds a special case (as already exist for some other resource managers) for SGE, changing the ``qstat`` call used by the qlauncher to specify the queue name *and* the user, then counting the lines present. 
SGE does not leave completed jobs in the ``qstat`` output to my knowledge (doesn't happen on our installation, but if anyone knows …

Fix SGE qlaunch rapidfire --maxjobs_queue detection

---

fireworks/core/rocket.py
fireworks/features/multi_launcher.py
fireworks/fw_config.py
fireworks/tests/multiprocessing_tests.py
fireworks/utilities/fw_utilities.py

Previously, in job packing mode, a sub job will exit prior to the finish of the whole job. Now, it is fixed, all the sub jobs will wait until there are no active FireWork launches

Fix the premature exit issue

---

docs/introduction.rst

Documentation > Introduction >  optional python examples >  rapidfire example
This example won't work unless FWorker is imported from fireworks.
thx to @saurabh02

Fixing Documentation - Introduction

---

fireworks/core/firework.py

wrap the gzipfile object in an io.TextIOWrapper instance so that python3 projects can use the trackers.

open compressed files in textmode to ensure py3k compatibility

---

fireworks/features/multi_launcher.py
fireworks/scripts/mlaunch_run.py

An option to exclude head node from compute node list is added to mlaunch. As MOM node is no longer available on Edison/Cori, heave jobs, e.g. VASP will also run on the head node. this option will help to reduce the presure on head node and therefore improve computational efficiecy if many nodes are used. By default, head node is not excluded. i.e. keep the node list as is.

Add Options to Leave Head Node Out in Job Packing

---

fireworks/__init__.py

Per Rasmus Karlsson's recent e-mail to fireworkflows mailing list, imports Tracker in fireworks.__init__ so it can be imported from fireworks directly for convenience.

Adds Tracker to core modules available to import from top-level fireworks namespace

---

docs/priority_tutorial.rst
fireworks/core/launchpad.py
fireworks/queue/queue_launcher.py
fireworks/scripts/qlaunch_run.py

* Adds qlaunching of specific fireworks, e. g. `qlaunch -r singleshot -f fw_id`
* Also added a few notes to priority_tutorial.rst about rlaunching and qlaunching specific fireworks.
Note that I changed the abbreviated flag for --fill_mode to -fm to avoid overlap with -f, which I thought should be the same for rlaunch and qlaunch.  They're part of separate parsers, so it's not strictly necessary, but might make things a little less confusing.

Qlaunch fw

---

fireworks/core/launchpad.py
fireworks/features/fw_report.py

Mongo Version:
```
db version v3.4.0
git version: f4240c60f005be757399042dc12f6addbc3170c1
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
allocator: tcmalloc
modules: none
build environment:
distmod: rhel62
distarch: x86_64
target_arch: x86_64
```
Package list:
```
FireWorks==1.3.9
Flask==0.11.1
Jinja2==2.8
MarkupSafe==0.23
PyYAML==3.12
Werkzeug==0.11.11
click==6.6
flask-paginate==0.4.5
gunicorn==19.6.0
itsdangerous==0.24
monty==0.9.6
paramiko==2.1.0
pyasn1==0.1.9
pymongo==3.4.0
python-dateutil==2.6.0
six==1.10.0
tabulate==0.7.7
wsgiref==0.1.2
```
After started webgui, when click links in Summary Reports, page shows internal error, console log is below:
```
(firework)[root@ops fireworks]# lpad webgui --host=0.0.0.0
* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2016-12-14 …
```

lpad webgui gives error when show report: OperationFailure: FieldPath field names may not contain '.'.

---

fireworks/user_objects/queue_adapters/common_adapter.py

It is strange that stdout from SLURM submission command is a raw bytes string. Anyway, I got a raw byte string in a Python3 environment. Now the code checks the type of "output_str" variable, if it is really a raw bytes string, convert it to UTF-8 str explicitly. Otherwise, the split() function will raise an error.

Ensure encoding of UTF-8 before parsing command output

---

fireworks/features/multi_launcher.py

In Python3, / is a float division operator, it will cause an error "TypeError: 'float' object cannot be interpreted as an integer".

Use Explicit Integer Division Operator to Make sub_nnodes Calculation Py3 Compatible

---

fireworks/flask_site/app.py

Avoids KeyError if one of two session vars for firework/workflow query filtering is not set.

Fix bug in webgui query filtering

---

fireworks/user_objects/queue_adapters/SLURM_template.txt

add Specifies a comma delimited list of generic consumable resources to SLURM_template.txt, to support manage the occupation of GPU.

add gres support to  SLURM_template.txt

---

fireworks/scripts/qlaunch_run.py

For at least one cluster I've encountered (PSC Bridges), the [default shell used by fabric](http://docs.fabfile.org/en/1.13/usage/env.html#shell) was not initializing with the configuration files I expected to give the proper environment for my qlauncher. This PR adds an option to the qlauncher for passing in the shell command that fabric will use.

Added qlauncher option for remote shell.

---

fireworks/core/rocket.py

If an error is raised before ping_stop and btask_stops have been defined the except block fails due to the variable being referenced before assignment. This PR fixes the problem78.

fix: always define variables used in except block

---

fireworks/user_objects/queue_adapters/common_adapter.py

Currently the SGE queue adapter requires the queue parameter to be set. This causes an issue for clusters where SGE is configured such that jobs are assigned a queue at run time, as it means the number of queuing jobs cannot be determined.
For these systems it is OK if the queue parameter is not set, therefore I have made this an optional parameter (similar to how it is handled in the SLURM section of the code).

Enable optional queue setting in SGE queue adapter

---

docs_rst/installation.rst

When going through the tutorials, I realized that the URL `www.mongolab.com` is not accessible anymore, and that it has (apparently) been replaced by `www.mlab.com`.
Therefore, this pull request replaces mongolab by mlab, where appropriate, the `.rst` source files.
Note: I did not modify the generated `.html` files, that are in `./docs`.

Replace mongolab with mlab

---

docs_rst/security_tutorial.rst
fireworks/core/launchpad.py

The existing SSL option in configuration file allows encrypted database connection, however it is insufficient if the server requires client authentication with a client certificate. This is the reason for this extension proposal. The change has been tested with local MongoDB servers in the group with and without SSL. No changes in the launchpad file are necessary for the non-SSL mode, for the previously implemented SSL mode (CA cert ) the ``ssl`` has to be set to ``true``. **NOTE**: The key ``ssl_ca_file`` was changed to ``ssl_ca_certs`` for more consistency with pymongo keys but the key name can be reverted before merging if there are many configurations in production which can get broken. However, the previous SSL support was not documented so that this might not be necessary.

Extended TLS/SSL configuration in launchpad file

---

fireworks/core/firework.py

In `Workflow.rerun_fw`, when you rerun a Firework, it will recursively go down and rerun all children, then children of that child etc:
https://github.com/materialsproject/fireworks/blob/9b26bb7037a12fcdcb8db17fb3fde9cdd7233686/fireworks/core/firework.py#L858-L880
For a fork/branch pattern (like below) this will scale badly as rerunning the `FIZZLED` FW at the top then reruns `FW1`, then `FW4`, then `FW5-7`, then `FW8`, but then it will rerun `FW2`, `FW4`, `FW5-7` again etc.  If you add another fork/branch below it will scale O(n^3, 4, 5), etc as you add more fork/branches.  I'm running a genetic algorithm, so I have ~60 fork/branches, so rerunning a FW using the launchpad just times out.
I've changed `rerun_fw` to only rerun children if the child was not `WAITING`.  This will assume that …

Added check in Workflow.rerun_fw to only rerun child if not waiting

---

fireworks/core/launchpad.py

I was getting annoyed with submitting a ~50,000 firework Workflow was, so I made a few changes which seem to work for me, but maybe there's something obvious I missed.
- Added optional quantity kwarg to `LaunchPad.get_new_fw_id` (allows multiple fw_ids to be taken at once)
- `LaunchPad._upsert_fws` with `reassign_all = True` now does fewer database transactions (3 in total, rather than N)

Performance for LaunchPad.add_wf

---

fireworks/user_objects/firetasks/tests/test_dataflow_tasks.py

This is a solution to Issue https://github.com/materialsproject/fireworks/issues/242. I simply skip the test on a non GNU/Linux platforms.

skip test_command_line_task_3 when platform is not GNU/Linux

---

fireworks/core/launchpad.py
fireworks/core/tests/test_launchpad.py

Task-level recovery has a bug in that LaunchPad.rerun_fws unsets the wrong spec key on a normal rerun.  This PR should fix.  Might want to wait on tests, something was a bit weird on my circle tests, but I think it's a config issue on my fork.

Recovery fix

---

fireworks/flask_site/app.py

I don't think it matters too much right now, but we should probably avoid hard-coding a secret key in a public repo? I think this is mostly used for session cookies and the like.

Remove hard-coded secret key

---

fireworks/scripts/lpad_run.py
fireworks/tests/cmd_line_test.sh

Very often we need to extend existing workflows and for that we initially used the python interface to the method `fireworks.core.firework.Workflow.append_wf` via a three-line separate python script. Much more convenient would be to use the `lpad` command for this rather general operation. In addition, often a workflow has to be dumped from the LaunchPad for editing or sharing. For these operations, two new sub-commands in the `lpad` command are suggested: `append_wflow` and `dump_wflow`. The added `lpad` help strings document the usage of the new commands and also the tests in `cmd_line_test.sh` are extended accordingly.

new sub-commands to lpad

---

fireworks/scripts/lpad_run.py

Previously would just return a slightly cryptic error.

Print help if no command supplied to lpad

---

fireworks/flask_site/templates/base.html

The fetched script (livereload.js) depends on a running LiveReload server, which is used only for development and can impact deployments (a server may not quickly 404 the file in part because the request is to a non-standard port, so the page may take tens of seconds to load).

flask_site: Remove unnecessary, performance-impacting script fetch

---

fireworks/scripts/lpad_run.py

This is important for running multiple `lpad webgui --server_mode` instances on a single host. It's also just a good idea to allow this argument in addition to the `host` and `port` params for the underlying `gunicorn` call.

Add optional `lpad webgui` argument for number of server processes

---

fireworks/core/launchpad.py
fireworks/core/tests/test_launchpad.py

I've found myself in need of a more efficient method of workflow addition to the launchpad lately (e. g. for adding thousands of workflows at a time), so I wrote a method that does it a bit more efficiently using some of mongo's bulk insertion functionality.
I'm not really sure if this is a good idea for the master branch (it seems less secure than adding them one at a time), but I figured I'd submit this PR to see if there was any feedback on how it might be adapted for general use (or if there's a better strategy), if there are any issues.
Also included rudimentary unit test.

Bulk insert add wfs

---

fireworks/core/firework.py
fireworks/core/tests/test_firework.py

- Removes FiretaskMeta.\_\_call__, moves required parameter checks to FiretaskBase.\_\_init__
- Adds \_\_getstate__, \_\_setstate__, \_\_reduce__" to FiretaskBase
- Adds basic unit tests for pickle/unpickle to fireworks/core/tests/test_firework.py
- Small adjustment to one assert check in FiretaskBaseTest, since \_\_call__ was removed
The current behavior before this update throws a ValueError during unpickle because of how unpickle rebuilds the object, executing the metaclass \_\_call__ method with no arguments.
Originally, I had a workaround in FiretaskMeta that checked whether the inputs to \_\_call__ were length zero, and if so then bypass checking the required parameters.  This approach didn't cover all cases where you want to enforce required parameters, for example, ScriptTask(). …

Add support for pickle/unpickle of Firetasks

---

fireworks/core/launchpad.py

While testing the new `bulk_add_wfs` function I realized that the fw_id are inserted with negative values in the fireworks collection. They should be updated explicitly also in the Fireworks instances before insert.

update fireworks' fw_ids in bulk insert

---

fireworks/core/launchpad.py
fireworks/core/tests/test_launchpad.py
fireworks/scripts/lpad_run.py

This PR introduces the possibility to delete all the launch directories associated with a workflow when calling delete_wf. I often use this option when deleting failed workflows, in order to avoid leaving large unreferenced temporary files in the file system. 
I thought that this may be of general interest.
If this is the case, two further modifications could be considered:
-  print the launch directories and add a check from the user before actually deleting them
- add warnings in case shutil.rmtree fails to delete the directory (with "onerror")

Option to delete launch dirs when deleting workflows

---

fireworks/user_objects/queue_adapters/SLURM_template.txt

Adding signal to the SLURM template. This can be used to tell SLURM to send a signal to the running proc before wall time. Especially useful to ensure you don't lose runs.

Add signal to SLURM template

---

fireworks/scripts/lpad_run.py

Most of the `lpad X_wflows -n NAME` functions don't work, this fixes that.
previously gave "Namespace has no attribute 'launches_mode'":
```
(gcmcworkflow) richards-imac:[~/test/gcmcworkflowtest]:$ lpad delete_wflows -n test
Traceback (most recent call last):
File "/Users/richardgowers/miniconda3/envs/gcmcworkflow/bin/lpad", line 11, in <module>
sys.exit(lpad())
File "/Users/richardgowers/miniconda3/envs/gcmcworkflow/lib/python3.6/site-packages/fireworks/scripts/lpad_run.py", line 1127, in lpad
args.func(args)
File "/Users/richardgowers/miniconda3/envs/gcmcworkflow/lib/python3.6/site-packages/fireworks/scripts/lpad_run.py", line 322, in delete_wfs
fw_ids = parse_helper(lp, args, wf_mode=True)
File "/Users/richardgowers/miniconda3/envs/gcmcworkflow/lib/python3.6/site-packages/fireworks/scri …
```

fixed lpad cli when performing wflow operations

---

fireworks/core/firework.py
fireworks/tests/test_workflow.py

`Workflow.state` isn't entirely reliable, for example in the Workflow below, this is reported as FIZZLED (in this case because a leaf node is WAITING).
From what I can tell, the only way to make the FIZZLED workflow state work is to check the spec of children (essentially FIZZLED == COMPLETED if all children are cool with it), but this will be slower because of the lazy attribute lookups.
I think this fixes it, unless I've missed some other corner cases

fixed Workflow.state

---

fireworks/user_objects/queue_adapters/SLURM_template.txt

Added two new queue adapter options: --mem and --mem-per-cpu to SLURM template.  This is useful for me and figured I would share it with the community at large.

Addition of memory options to SLURM queue template

---

fireworks/core/firework.py
fireworks/core/tests/test_launchpad.py

I have realized that this commit https://github.com/materialsproject/fireworks/commit/d9a71ac27cfd025af39f507137c407657e17dd38 have caused a regression. 
Consider the case with a fw `fw1` with one child `fw2` and the whole wf is completed. Trying to rerun `fw1` now results in having both `fw1` and `fw2` `READY`, instead of `fw2` being `WAITING`. 
Here is a piece of code demonstrating the problem 
```python
from fireworks import LaunchPad, Firework, Workflow
from fireworks.core.rocket_launcher import rapidfire
from fireworks.examples.custom_firetasks.hello_world.hello_world_task import HelloTask
lp = LaunchPad.auto_load()
#lp.reset()  
fw1 = Firework([HelloTask()])
fw2 = Firework([HelloTask()], parents=[fw1])
wf = Workflow([fw1, fw2])
old_new = lp.add_wf(wf)
fw_ids = list(old_new.values()) …
```

fix regression when rerunning one firework with dependencies 

---

fireworks/flask_site/templates/fw_details.html

Otherwise Chrome won't load "insecure content" over http.

Don't hard-code http:// - can use https://

---

fireworks/core/firework.py
fireworks/core/launchpad.py
fireworks/core/tests/tasks.py
fireworks/core/tests/test_launchpad.py
fireworks/fw_config.py

This PR addresses the problem discussed in #313.
At this stage I have implemented only the saving to gridfs. While I would have liked to include the option to switch to the deletion of the data, I came across a problem that I did not consider beforehand:  
at present, the call to `Workflow.apply_action` is performed inside `Workflow.refresh` and the Launch object used there is not the one available in `complete_launch`, so it is downloaded from the DB there. With this configuration, if the action is not stored anywhere it will not be applied. 
A possible workaround would be to make the launch an argument of `refresh` and propagate the original object from `complete_launch` (through `Launchpad._refresh_wf`), but I am not sure if it would be a good idea to do that just to allow this option. …

[WIP] Solve DocumentTooLarge error for Launch

---

docs_rst/dataflow_tasks.rst
docs_rst/pytask.rst

Recently I discovered keyword and type inconsistencies in two examples in the upstream/master branch. These inconsistencies seem to be leftovers after refactoring the PyTask before a merge some time ago. The relevant tests are not affected of course.

corrected keyword 'function'->'func' and outputs string -> list

---

.circleci/config.yml
fireworks/core/launchpad.py
fireworks/core/tests/test_launchpad.py

After the last changes to `LaunchPad`, users were always authenticating against the admin database. Therefore, they could not access databases that they were users of. These changes ensure that a user is authenticating against the database that they want to access, and not the admin database by default.
* A *not_the_admin_db* database is created by circle ci with a single user *myuser*
* The `authSource` is always passed into the `MongoClient` constructor
* Tests ensure that *myuser* can only authenticate against the database that they are a part of
* Tests ensure that the `authSource` is inferred from the database that the user wants access to

Further authentication issues in LaunchPad construction

---

fireworks/core/launchpad.py
fireworks/scripts/lpad_run.py

This PR contains two modifications.
The first is a fix for a minor problem that I have ancountered in ``rerun_fw`` in combination with the ``recover_launch`` option. The ``recover_launch`` dictionary is coming from the ``checkpoint`` keyword in the Launch history. This can contain the serialized version of an MSONable object. This gets deserialized while loading, but when doing the
```python
self.fireworks.find_one_and_update({"fw_id": fw_id}, set_spec)
```
it is not serialized and the update of a dictionary containing this object fails. I added a ``recursive_dict`` that solves the problem and should be harmless for all the other cases. 
I just have the doubt if this should instead be done inside ``get_recovery``. The API of that method is not really explicit about what should be its …

small updates

---

fireworks/flask_site/templates/wf_details.html

Browsers like Firefox refuse to load files over http if the host page is served over https.

Load according to server scheme (https or http)

---

fireworks/scripts/lpad_run.py

```
File "/global/home/users/phuck/mp_prod/codes/fireworks/fireworks/scripts/lpad_run.py", line 361, in detect_lostruns
launch_query = ast.literal_eval(args.launch_query) if args.host else None
AttributeError: 'Namespace' object has no attribute 'host'
```

args check, fixes #331

---

fireworks/core/rocket.py

For the special spec argument "_pass_job_info", it would be useful to get the state of the parent FWs. Normally, the state of a parent should be "COMPLETED", however, if we also have the special spec argument "_allow_fizzled_parents" this is not always the case. It would be easier to pass the job info for this situation than to load it from the collection during a FW.

Feature request - adding state of the FW for _pass_job_info

---

fireworks/scripts/lpad_run.py

Not sure if it is really used, but currently the `-t` option for `lpad get_wflows` fails in case of 1 or 0 workflows listed

fix -t option in lpad get_wflows

---

fireworks/user_objects/firetasks/filepad_tasks.py
fireworks/utilities/filepad.py

So far, it has only been possible to store text files in the filepad. Trying to store binary files threw an error. This simple modification stores all files as binary in the filepad. However, the filepad behavior would change in such a way that the responsibility of correctly encoding / decoding text files is passed on to the user.

Allow binary files in filepad

---

fireworks/core/rocket.py

Use mod_spec instead of update_spec to pass on out-/infiles along Fireworks. 
That allows for files to come from several merging branches of a workflow as in
as long as they are labeled differently.
It seemed to me that with the previous "update_spec" utilization, only (a set of) _files_out from one branch were passed onto the child firework, depending on which branch executed last.

_files_in from an arbitrary number of merging workflow branches

---

fireworks/core/launchpad.py
fireworks/scripts/lpad_run.py

I have found two potential problems related to the LaunchPad.
The first is in the `lpad` command. Since the `-l` option is assigned a default in argparse the `-c` is never taken into account. I removed the default and modified the `parse_helper` function so that it should properly consider the `-c` option as well.
The second problem concerns the fetching of the Launches from the database. 
Currently the launches are fetched in this way:
```python
list(self.launches.find({'launch_id': {"$in": fw_dict['launches']}}))
```
My understanding of how MongoDB works is that this query does not guarantee the order of the launches (and archived launches as well). This list is then passed directly to the Firework `__init__`. The incorrect order might be an issue, since in some portions of the code the …

fix for lpad

---

docs_rst/security_tutorial.rst
fireworks/core/launchpad.py

MongoDB supports external authentication mechanisms (x509 certificates, LDAP, Kerberos token) instead of internal username/password credentials. To enable them in FireWorks the ``authmechanism`` keyword has to be added to the LaunchPad object. This branch enables this feature and has been tested with x509 CA-signed certificates. The documentation is extended accordingly. LDAP, Kerberos and other external methods have not been tested.

Authentication from external sources

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md
README.md
docs_rst/index.rst

The FireWorks support forum is moving from Google Groups to Discourse (https://hackingmaterials.discourse.group/c/fireworks). I've updated all references to Google Groups to point to the new forum.
However, as we are not migrating old posts to the new forum, I've left in links that point to specific  Google Groups posts. Specifically, these are:
```
./fireworks/core/launchpad.py:                # see: https://groups.google.com/forum/#!topic/fireworkflows/oimFmE5tZ4E
./docs_rst/installation.rst:.. note:: We suggest that you use Python 2.7.3 or higher, especially in production. There is a `bug <https://groups.google.com/forum/#!topic/modwsgi/DW-SlIb07rE>`_ in Python 2.7.2 that could affect FireWorks (although we haven't seen any problems yet). As of FireWorks v0.7, Python 3.3 and higher …
```

Update Google Groups references to Discourse

---

fireworks/user_objects/queue_adapters/common_adapter.py
fireworks/user_objects/queue_adapters/tests/test_common_adapter.py

On one of our clusters when submitting a job we get the message "Submitted batch job xxxx on cluster name_of_the_cluster" instead of the standard message "Submitted batch job xxxxx" , leading to a failure in parsing the id. The PR fixes this case.
**N.B.** the current modification changes the behavior for SLURM: up to now (only for SLURM!)  `_parse_jobid` returned an int, while now it will return a string, as for all the other queue managers. This does not seem to have any effect, since the id is eventually converted back to a string before storing it: 
https://github.com/materialsproject/fireworks/blob/master/fireworks/core/firework.py#L456
Notice however that, even without this modification, the docstring for `submit_to_queue` is inconsistent, since it sometimes returns a string and …

update common adapter for SLURM

---

fireworks/queue/queue_launcher.py
fireworks/scripts/qlaunch_run.py
fireworks/user_objects/queue_adapters/common_adapter.py

Sometimes the queuing system is not responsive and when running `qlaunch`the check for the number of jobs goes in timeout. Two improvements implemented here to avoid this issue:
* if the maximum jobs in the queue is 0 (no limit), do not check the current number of jobs. 
* added a timeout option to the `CommonAdapter`. Before the timeout was hardcoded to 5 seconds.

avoid checking the number of jobs in the queue if not needed

---

fireworks/user_objects/firetasks/fileio_tasks.py

Currently, the FireTasks as implemented in fileio_tasks are missing some required and optional parameters. 
Adequate tags are added in order to pass the consistency check upon initialization of the FiretaskBase.

params-fix

---

fireworks/core/firework.py

Tracking files in text mode used to cause Fireworks to fail if encoding issues arose.
This pull request or specifying a particular encoding, i.e. "utf-8" should avoid such failures.

Avoid failures due to encoding issues in tracker

---

fireworks/utilities/dagflow.py
fireworks/utilities/tests/test_dagflow.py

This solves the following issues:
* https://github.com/materialsproject/fireworks/issues/398: missing global import of `DAGFlow` class in the tests
* https://github.com/materialsproject/fireworks/issues/399: caused by some changes in python-igraph `Graph.copy()` method or due to change in python 3.8 deepcopy behavior

bugfixes: global import of dagflow module; copy() of dagflow replaced

---

fireworks/core/rocket.py

I suggest removing this particular elif clause, as it leads to the diamond dependency issue described in the comment.

BUG (?): no dropping of desired input files in diamond dependency

---

fireworks/flask_site/gunicorn.py
setup.py

web gui fails with gunicorn versions >= 20, https://github.com/materialsproject/fireworks/issues/401

BUG: prevents https://github.com/materialsproject/fireworks/issues/401

---

fireworks/user_objects/firetasks/filepad_tasks.py
fireworks/user_objects/firetasks/tests/test_filepad_tasks.py
fireworks/utilities/dict_mods.py

A suggestion:
Turns the previously contributed "GetFilesByQueryTask" into something useful:
-  Allows for nested queries to be stored by using "->" instead of "." separator.
-  Different options to handle a priori uncertain number and names of queried files (see task's doc string)
- Tests for these added features (also serving documentation purposes)
Other additions:
- Use with-statement to enforce closing all file streams in other FilePad-Task tests, avoid warnings
- Tiny helper function "arrow_to_dot" within "utilities/dict_mods.py" facilitates "->" to "." conversion.
Best regards,
Johannes

Extended get files by query task

---

fireworks/core/firework.py

but along all decendants down to workflow leaves by adding a
'propagate' flag to FWAction. 
A typical usecase is some descriptive metadata that is not available a priori, but arises at some point along the workflow as a result of some task. That metadata is supposed to be valid for all dependent FireWorks and therefore should trickle down the dependency graph.

ENH: Allow propagating modified spec not only to direct children,

---

fireworks/scripts/lpad_run.py
fireworks/utilities/dagflow.py
fireworks/utilities/tests/test_dagflow.py

Solves issue https://github.com/materialsproject/fireworks/issues/411. Only assertions have not been replaced with specific exceptions. Though the issued `AssertionError` can still be trapped by calling functions (see examples in the tests).

Reorganized DAGFlow class

---

fireworks/core/launchpad.py
fireworks/scripts/lpad_run.py

This is another loose suggestion for extension: Often, I want to quickly submit a joint query between Fireworks and Workflows, i.e. get an overview on all FIZZLED Fireworks in a particular workflow. Here is an extension to the Launchpad and its command line interface to avoid the "detour" via direct MongoDB queries. One particular consideration for discussion would be how to distinguish between CLI options aimed at selecting Fireworks query and such aimed at selecting Workflows. I chose options prefixed with 'fw' and 'wf' respectively here, i.e.
lpad get_fws_in_wflows -wfi 38710 -fwq '{"state":"FIZZLED","name":{"$regex":"gmx_mdrun$"}}' -d all
would yield all Fireworks matching the 'fwq' query within the Workflow identified by 'wfi'.

ENH: Joint queries on Fireworks and Workflows from command line

---

fireworks/utilities/dagflow.py

Analogous to Ivan's `to_dot` functionality, this adds a `plot_wf` function to directly generate a graph plot of a workflow. This allows to visually look at the graph directly from some interactive python session (i.e. IPython or Jupyter Notebook) before actually adding the workflow to the LaunchPad, as shown here:
To allow for looking at possibly erroneous graphs, I suggest to "weaken" assertions on the dataflow into warnings.

ENH: dagflow direct plot

---

fireworks/user_objects/firetasks/fileio_tasks.py

can as well be specified nested below files, i.e. "files": [ {'src': ..., 'dest': ...}]

BUG: parameter dest is not required in FileTransferTask

---

.gitignore
fireworks/scripts/lpad_run.py

Fix the `TypeError: cannot pickle '_thread.lock' object` Issue #416 by not spawning a webserver process.
It could just call `webbrowser.open()` without additional parallelization, but this spawns a thread to call it to preserve the delay that gives the web server more time to get ready to serve pages.
I tested this on a Mac with Chrome, both in the cases where Chrome was already running and not. I didn't test other OSs or browsers, but it's using stock Python APIs. I tested this in Python 3.8.6. It should be fine in other Python releases, although the Python docs listed the `threading` module under "Optional Operating System Services" in Python 2.7 -- it's certainly present in the Mac Python 2.7.16.
Note: When `webbrowser.open(url)` needs to launch Chrome, Chrome opens the Fireworks `url` …

Don't fork a process to start the web server -- Fix #416

---

fireworks/user_objects/queue_adapters/SLURM_template.txt

Hi FireWorks developers,
This PR adds a GPU option to the SLURM template
I'm at NERSC and thinking about running FireWorks on Perlmutter. I wanted to make it easier for users to do this without manually editing the SLURM template themselves.
Best regards,
Laurie

add gpu option to slurm template

---

fireworks/features/fw_report.py
fireworks/utilities/dict_mods.py

Fixes below warnings in Python 3.8
```
find . -iname '*.py' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}          
./fireworks/features/fw_report.py:146: SyntaxWarning: "is" with a literal. Did you mean "=="?
if style is 'bar':
./fireworks/features/fw_report.py:149: SyntaxWarning: "is" with a literal. Did you mean "=="?
elif style is 'fill':
./fireworks/utilities/dict_mods.py:81: DeprecationWarning: invalid escape sequence \w
if (not re.match('__\w+__', i)) and callable(getattr(self, i)):
```

Fix syntax warning over comparison of literals using is.

---

fireworks/core/rocket.py

Use is_alive in favour of isAlive for Python 3.9 compatibility.

---

fireworks/features/fw_report.py
fireworks/flask_site/app.py
fireworks/utilities/dagflow.py
setup.py

This PR adds `wf_to_graph` [from here](https://git.io/JO6L8) to `fireworks/utilities/dagflow.py` as discussed in [atomate#638](https://github.com/hackingmaterials/atomate/issues/638#issuecomment-824273303).
It also refactors `state_to_color` to have a single source of truth in `fireworks/features/fw_report.py`. Let me know if this is unwanted or should be placed somewhere else.

add mpworkshop's wf_to_graph + SSOT for state_to_color

---

fireworks/core/rocket.py

Use current_thread instead of currentThread method that was deprecated in Python 3.10.

---

fireworks/core/launchpad.py
fireworks/core/tests/test_launchpad.py
fireworks/scripts/lpad_run.py
fireworks/tests/mongo_tests.py
fireworks/utilities/tests/test_update_collection.py
fireworks/utilities/update_collection.py

Closes #322.
`count()` was deprecated in pymongo 3.7.2

pymongo count() --> count_documents()

---

fireworks/scripts/lpad_run.py

print() instead of raise ValueError on user-aborted confirmation prompt

---

fireworks/scripts/lpad_run.py

Closes #467.
Did some local testing with this new default and found a faster startup time but no noticeable degrade in the GUI's performance. Tested on a DB with ~5400 fireworks.

Reduce default number of webgui workers to 1

---

docs_rst/conf.py
tasks.py

Overlooked 2 files in #478 that still use the py38-only way of importing `importlib.metadata`.

Fix importlib import

---

fireworks/utilities/fw_serializers.py

It appears a `pytest` import was added in the path of `USER_PACKAGES`
https://github.com/materialsproject/fireworks/blob/51aa296dff9cd0411ad9165973dd4bc5c4a5c7aa/fireworks/fw_config.py#L20
And the part of the code that is meant to deal with the exception has a call to `traceback.print_exc(ex)`
which is treating the `ex` exception as the `limit` parameter. 
https://github.com/materialsproject/fireworks/blob/635fca928777610e5933a4f197c0be024aaa82ef/fireworks/utilities/fw_serializers.py#L362
Code for `print_exc`:
```
Signature: traceback.print_exc(limit=None, file=None, chain=True)
Source:   
def print_exc(limit=None, file=None, chain=True):
"""Shorthand for 'print_exception(*sys.exc_info(), limit, file)'."""
print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
File: …
```

qlaunch not working on a fresh install

---

docs_rst/installation.rst
fireworks/core/launchpad.py

Previous code and docs for using the URI mode of a DB is based on mLab, which has been acquired by MongoDB Atlas. This PR fixes the URI mode. 
- now, when using the URI mode, the database name need to be explicitly provided 
- updated the corresponding docs

Fix using URI mode to provide DB info

---

fireworks/user_objects/queue_adapters/PBS_template.txt

Dear FireWorks developers,
In testing FireWorks on ALCF Polaris I found that they require the PBS filesystems flag. I have tested it in my own local adapter and now am adding it to your PBS template.
Please let me know if you have any questions. 
Thank you,
Laurie

add pbs filesystems option for alcf polaris

---

.pre-commit-config.yaml
fireworks/flask_site/util.py

- The WebGUI crashes when some configuration variables cannot be access,  the `.get(..., None)` pattern fixes this and the workflows render for me.
- The `isort` version in the current pre-commit crashes but bumping it to `5.11.5` fixes this.

Fix `webgui` KeyError

---

fireworks/flask_site/app.py

I noticed some restarted jobs not rendering because the `_id` fields are pulled from the `archived_launches` which results in the following error in the `webgui`:
```
File "/Users/shen9/local/Caskroom/miniconda/base/envs/mp/lib/python3.9/site-packages/flask/json/provider.py", line 122, in _default
raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
```
And does not allow the page to be opened. This PR should fix that problem.

[BUG FIX] remove `_id` from `archived_launches`

---

.pre-commit-config.yaml
docs_rst/conf.py
fireworks/core/tests/test_firework.py
fireworks/core/tests/test_launchpad.py
fireworks/scripts/lpad_run.py
fireworks/scripts/mlaunch_run.py
fireworks/scripts/qlaunch_run.py
fireworks/scripts/rlaunch_run.py
fireworks/tests/master_tests.py
fireworks/tests/mongo_tests.py
fireworks/user_objects/firetasks/tests/test_fileio_tasks.py
fireworks/user_objects/firetasks/tests/test_filepad_tasks.py
fireworks/utilities/tests/test_dagflow.py
tasks.py

Python code and CLI are currently inconsistent. Python calls functions `get_wflows`, `delete_wfs`, `reignite_wfs`, etc. while CLI calls them `get_wfs`, `delete_wflows`,` `reignite_wflows`, etc.
This PR adds `argparse.subparser(aliases: list[str])` so that both `get_wfs` and `get_wflows` etc. work.

Add `<action>_wfs` aliases for all `lpad <action>_wflows` commands

---

fireworks/scripts/lpad_run.py
fireworks/user_objects/firetasks/dataflow_tasks.py
fireworks/user_objects/firetasks/tests/test_dataflow_tasks.py
fireworks/user_objects/queue_adapters/tests/test_common_adapter.py
fireworks/utilities/fw_serializers.py
pyproject.toml

Closes #516 
Starting from release 0.15, ruamel.yaml has [introduced a new API](https://yaml.readthedocs.io/en/latest/api/). Starting with ruamel.yaml release 0.18 the old interface used in fireworks is depricated and removed. A future deprecation warning is shown with the releases in between. The warning turns into an `AttributeError` with ruamel.yaml >=18.0 (see issue #516 for more details).
Major changes:
- adapted all instances of `yaml.safe_load()` and `yaml.safe_dump()` to the new interface
If this is work in progress, what else needs to be done?
- 
```sh
```

Adaptions to ruamel.yaml new API

---

docs_rst/firetask_tutorial.rst

Major changes:
Just fixed a a documentation typo.
If this is work in progress, what else needs to be done?
N/A.
```sh
```
None of the checklist apply.

DOC: Fix typo in firetask tutorial

---

setup.py

In Windows 10, a bug occurs when installing software via pip install. The reason is that the encoding method was not specified when reading the Readme file in the setup. Therefore, this modification was made.
python verision: 3.10
numpy version: 1.25.2
```
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [17 lines of output]
Traceback (most recent call last):
File "<string>", line 15, in <module>
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 815: illegal multibyte sequence
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
× …
```

fix encoding bugs in setup.py

---

docs_rst/config_tutorial.rst
fireworks/core/rocket.py
pyproject.toml

Closes #514
Some logging in the modules `rocket.py` and `rocket_launcher.py` has unexpected behavior. See issue #514 for more details.
Major changes:
- Describe in the docs the logging level used in `rocket.py`
- Replace `print()` with `logger.log()`
If this is work in progress, what else needs to be done?
- 
```sh
```

Logging in rocket.py and launch_rocket.py

---

fireworks/core/launchpad.py

```py
launchpad.delete_fws([1087263487612])
File ~/dev/fireworks/fireworks/core/launchpad.py:584, in LaunchPad.delete_fws(self, fw_ids, delete_launch_dirs)
582     fw_dict = self.fireworks.find_one({"fw_id": fw_id})
583     # if fw_dict:
--> 584     potential_launch_ids += fw_dict["launches"] + fw_dict["archived_launches"]
586 launch_ids = [
587     launch_id
588     for launch_id in potential_launch_ids
(...)
592     )
593 ]
595 if delete_launch_dirs:
TypeError: 'NoneType' object is not subscriptable
```

Fix `lpad.delete_fws` if `fw_id` not found

---

.circleci/config.yml
.github/workflows/test.yml
requirements.txt
setup.py

also bump `pymongo` to v4.0.0 in `requirements.txt` and `setup.py`
CircleCI was running largely (fully?) identical `pytest` and `pytest_pymongo4` jobs (i.e. duplicate work). now running single job but in both GitHub Action and CircleCI with `pymongo` 4. we can safely remove CircleCI but i don't have permissions

Migrate CI tests from CircleCI to GitHub Actions

---

fireworks/core/rocket.py

Closes #532
Major changes:
- Fix: replace `copy_tree` from deprecated `distutils` package with `copytree` from the `shutil` package
If this is work in progress, what else needs to be done?
```sh
```

Replace copy_tree from distutils with copytree from shutil

---

fireworks/core/launchpad.py

Closes #544 
Major changes:
- feature 1: use LazyFirework in `LaunchPad.append_wf()`
None
```sh
```

Use LazyFirework object to construct Workflow for extending

---

fireworks/fw_config.py
fireworks/utilities/fw_serializers.py
setup.cfg

Closes #546 
Major changes:
- feature 1: Separate `to_dict()` from the actual serialization to YAML/JSON and writing to file.
- fix 1: flake8 E501 line too long
- fix 2: pylint E1135 unsupported-membership-test
None
```sh
```

[Feature Request]: Improve behavior of ‎FWSerializable.to_file

---

docs_rst/guide_to_writing_firetasks.rst
fireworks/core/firework.py
fireworks/examples/custom_firetasks/if_function/if_nonstrict.py
fireworks/examples/custom_firetasks/if_function/if_strict.py
fireworks/tests/mongo_tests.py

Closes #549
The attributes `additions` and `detours` of `FWAction` class allow dynamic extensions of a workflow. A workflow extension has a parameter `fw_ids` that is a list of IDs of all parent nodes for the extension to be linked. Workflow extensions via `additions` and `detours` are restricted to the parent that is the Firework containing the Firetask returning these actions (quite natural) and this parameter contains only this ID.
In some cases, for example to implement true lazy evaluation with FireWorks, it is necessary to be able to specify additional parent nodes if their evaluation becomes necessary. A typical example is to implement non-strict `if` function but there are more. See [this issue](https://gitlab.kit.edu/kit/virtmat-tools/vre-language/-/issues/449) for more details. …

[Feature Request] Generalize additions and detours actions in a new append_wfs action
